### ISSUE TITLE
Where to find oauth2 key

### ISSUE THREAD

**Issue by jedfonner** [RasikaWarade/chrome-extension-mv3-firebase-boilerplate#1]
Thank you very much for this repo, it's been super helpful.  I have one question: where did you get the oauth2 `key` that you added to the manifest file?  I checked all the docs and I can't seem to find this anywhere.  Thanks in advance!

**Comment by RasikaWarade** [comment]
Sure! thank you for reaching out.

I basically followed the `Creating an OAuth Client` guideline to obtain the oauth2 `key` from the firebase [quickstart guide](https://firebaseopensource.com/projects/firebase/quickstart-js/auth/chromextension/readme/#setting_up%20this%20sample), but here are my detailed steps :


**Steps:**
- Go to [GCP Project Console](https://console.cloud.google.com/home)
- Search for Credentials. You should see something like this in the UI
<img width="598" alt="image" src="https://user-images.githubusercontent.com/9664493/156951059-f1faa122-a665-4020-90d9-fbc8e408abf7.png">

- Select `Create Credentials`
- Select `OAuth Client ID`
- Select `Chrome App`
- Enter your Chrome Extension/App ID
- Note the `Client ID` which is the `oauth2 key`
<img width="657" alt="image" src="https://user-images.githubusercontent.com/9664493/156951195-8ecf357e-f7d2-416b-8b41-3f69cf8ad1b9.png">

**Comment by jedfonner** [comment]
Hi, thanks very much.  I think the "Client ID" you mention above is what is supposed to go into the `client_id` field of the `oauth2` key.  I was asking about the Public Key details you have in the `key` key underneath `oauth2`.  

![Screenshot_20220306_203116](https://user-images.githubusercontent.com/344481/156952995-e96ec7b7-d366-43ae-a868-51a91db76b43.png)

However, I think I may have found the answer here: https://developer.chrome.com/docs/apps/app_identity/
It admits to the steps being "not the most graceful task" but basically boils down to getting the public key from the extension folder in the user's data directory.  Wild.
